### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 995085226** [zhangqian666/shop-front-android#3]
07-16 15:12:16.146 6518-6518/com.zack.shop E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zack.shop, PID: 6518
    java.lang.RuntimeException: Canvas: trying to draw too large(230664800bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.view.View.getDrawableRenderNode(View.java:19450)
        at android.view.View.drawBackground(View.java:19386)
        at android.view.View.draw(View.java:19183)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.View.draw(View.java:18920)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
        at android.view.View.draw(View.java:19195)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by 530l** [comment]
大佬，怎么后台代码跑不起来

**Comment by zhangqian666** [comment]
后台代码需要相应的数据库 redis等配置

**Comment by wq824372880** [comment]
我是android，后台接口怎么不通了，前几天还可以呀？

**Comment by zhangqian666** [comment]
> 我是android，后台接口怎么不通了，前几天还可以呀？

现在可以了。换了新的服务器

**Comment by jinhuizxc** [comment]
请问后台服务器的ip地址是什么，没有后台地址哦

**Comment by zhuangzong** [comment]
后台服务器已停，不知道什么时候开启




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年1月19日(星期天) 下午5:54
收件人: "zhangqian666/shop-front-android"<shop-front-android@noreply.github.com&gt;; 
抄送: "康宗鹏"<491055371@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zhangqian666/shop-front-android] 启动报错 (#3)




请问后台服务器的ip地址是什么，没有后台地址哦

**Comment by jinhuizxc** [comment]
服务器不是你自己搭建的么？

**Comment by zhuangzong** [comment]
是啊，好久没掏钱了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年1月19日(星期天) 下午5:57
收件人: "zhangqian666/shop-front-android"<shop-front-android@noreply.github.com&gt;; 
抄送: "康宗鹏"<491055371@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zhangqian666/shop-front-android] 启动报错 (#3)




服务器不是你自己搭建的么？

**Comment by jinhuizxc** [comment]
后台本地代码可以给我一份么，想本地跑下试试哦
